server:
  port: 10006

spring:
  application:
    name: app-service
  profiles:
    active: master
#  cloud:
#    config:
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
#      discovery:
#        service-id: config-service
#        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10111/eureka