server:
  port: 10008

spring:
  application:
    name: gateway-service
  profiles:
    active: master
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/product-service/**
          filters:
          - StripPrefix=1

        - id: account-service
          uri: lb://account-service
          predicates:
          - Path=/account-service/**
          filters:
          - StripPrefix=1

        - id: admin-service
          uri: lb://admin-service
          predicates:
          - Path=/admin-service/**
          filters:
          - StripPrefix=1

        - id: app-service
          uri: lb://app-service
          predicates:
          - Path=/app-service/**
          filters:
          - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/order-service/**
          filters:
          - StripPrefix=1

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
          - Path=/wallet-service/**
          filters:
          - StripPrefix=1
#  cloud:
#    config:
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
#      discovery:
#        service-id: config-service
#        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10111/eureka